server:
  port: 80
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    #关闭自我保护机制，保证能剔除失去心跳的实例
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  instance:
    hostname: eureka
spring:
  application:
    name: eureka
logging:
  file: ${log.path:../logs}/${spring.application.name}.log
  level:
    org.springframework: debug